server:
  port: 8686
spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/city
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
            ddl-auto: update
      show-sql: true
      defer-datasource-initialization: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  mustache:
    check-template-location: false
  cache:
    type: simple

logging:
  level:
    org:
      atmosphere: warn
vaadin:
  launch-browser: true
  whitelisted-packages: "com.vaadin,org.vaadin,dev.hilla,com.example.application"