server:
  port: 8686
spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/city
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
            ddl-auto: create-drop
    open-in-view: false
  cache:
    type: simple