server:
  port: 8686
spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/city
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
            ddl-auto: update
    open-in-view: false
  mustache:
    check-template-location: false
  cache:
    type: simple

logging:
  level:
    org:
      atmosphere: warn
